// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  getActivitiesM3TerM3TerIdActivitiesGet,
  getDailyM3TerM3TerIdDailyGet,
  getMonthOfYearM3TerM3TerIdMonthYearMonthGet,
  getProposalProposalTxHashGet,
  getWeeklyM3TerM3TerIdWeeklyGet,
  getWeeksOfYearM3TerM3TerIdWeeksYearGet,
  type Options,
  readRootGet,
} from "../sdk.gen";
import type {
  GetActivitiesM3TerM3TerIdActivitiesGetData,
  GetActivitiesM3TerM3TerIdActivitiesGetError,
  GetActivitiesM3TerM3TerIdActivitiesGetResponse,
  GetDailyM3TerM3TerIdDailyGetData,
  GetDailyM3TerM3TerIdDailyGetError,
  GetDailyM3TerM3TerIdDailyGetResponse,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetError,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse,
  GetProposalProposalTxHashGetData,
  GetProposalProposalTxHashGetError,
  GetProposalProposalTxHashGetResponse,
  GetWeeklyM3TerM3TerIdWeeklyGetData,
  GetWeeklyM3TerM3TerIdWeeklyGetError,
  GetWeeklyM3TerM3TerIdWeeklyGetResponse,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetData,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetError,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse,
  ReadRootGetData,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) =>
  createQueryKey("readRootGet", options);

/**
 * Read Root
 *
 * Welcome message to our beloved users.
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof readRootGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readRootGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readRootGetQueryKey(options),
  });

export const getDailyM3TerM3TerIdDailyGetQueryKey = (
  options: Options<GetDailyM3TerM3TerIdDailyGetData>,
) => createQueryKey("getDailyM3TerM3TerIdDailyGet", options);

/**
 * Get Daily
 *
 * Get daily energy usage aggregate.
 */
export const getDailyM3TerM3TerIdDailyGetOptions = (
  options: Options<GetDailyM3TerM3TerIdDailyGetData>,
) =>
  queryOptions<
    GetDailyM3TerM3TerIdDailyGetResponse,
    GetDailyM3TerM3TerIdDailyGetError,
    GetDailyM3TerM3TerIdDailyGetResponse,
    ReturnType<typeof getDailyM3TerM3TerIdDailyGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDailyM3TerM3TerIdDailyGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDailyM3TerM3TerIdDailyGetQueryKey(options),
  });

export const getWeeklyM3TerM3TerIdWeeklyGetQueryKey = (
  options: Options<GetWeeklyM3TerM3TerIdWeeklyGetData>,
) => createQueryKey("getWeeklyM3TerM3TerIdWeeklyGet", options);

/**
 * Get Weekly
 *
 * Get weekly energy usage aggregate.
 */
export const getWeeklyM3TerM3TerIdWeeklyGetOptions = (
  options: Options<GetWeeklyM3TerM3TerIdWeeklyGetData>,
) =>
  queryOptions<
    GetWeeklyM3TerM3TerIdWeeklyGetResponse,
    GetWeeklyM3TerM3TerIdWeeklyGetError,
    GetWeeklyM3TerM3TerIdWeeklyGetResponse,
    ReturnType<typeof getWeeklyM3TerM3TerIdWeeklyGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWeeklyM3TerM3TerIdWeeklyGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWeeklyM3TerM3TerIdWeeklyGetQueryKey(options),
  });

export const getWeeksOfYearM3TerM3TerIdWeeksYearGetQueryKey = (
  options: Options<GetWeeksOfYearM3TerM3TerIdWeeksYearGetData>,
) => createQueryKey("getWeeksOfYearM3TerM3TerIdWeeksYearGet", options);

/**
 * Get Weeks Of Year
 *
 * Get energy usage of all weeks of specified year.
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 * :param year: Description
 * :type year: int
 */
export const getWeeksOfYearM3TerM3TerIdWeeksYearGetOptions = (
  options: Options<GetWeeksOfYearM3TerM3TerIdWeeksYearGetData>,
) =>
  queryOptions<
    GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse,
    GetWeeksOfYearM3TerM3TerIdWeeksYearGetError,
    GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse,
    ReturnType<typeof getWeeksOfYearM3TerM3TerIdWeeksYearGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWeeksOfYearM3TerM3TerIdWeeksYearGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWeeksOfYearM3TerM3TerIdWeeksYearGetQueryKey(options),
  });

export const getMonthOfYearM3TerM3TerIdMonthYearMonthGetQueryKey = (
  options: Options<GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData>,
) => createQueryKey("getMonthOfYearM3TerM3TerIdMonthYearMonthGet", options);

/**
 * Get Month Of Year
 *
 * Get energy usage of a month in specified year.
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 * :param year: Description
 * :type year: int
 * :param month: Description
 * :type month: int
 */
export const getMonthOfYearM3TerM3TerIdMonthYearMonthGetOptions = (
  options: Options<GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData>,
) =>
  queryOptions<
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse,
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetError,
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse,
    ReturnType<typeof getMonthOfYearM3TerM3TerIdMonthYearMonthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMonthOfYearM3TerM3TerIdMonthYearMonthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMonthOfYearM3TerM3TerIdMonthYearMonthGetQueryKey(options),
  });

export const getActivitiesM3TerM3TerIdActivitiesGetQueryKey = (
  options: Options<GetActivitiesM3TerM3TerIdActivitiesGetData>,
) => createQueryKey("getActivitiesM3TerM3TerIdActivitiesGet", options);

/**
 * Get Activities
 *
 * Get activities of a m3ter
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 */
export const getActivitiesM3TerM3TerIdActivitiesGetOptions = (
  options: Options<GetActivitiesM3TerM3TerIdActivitiesGetData>,
) =>
  queryOptions<
    GetActivitiesM3TerM3TerIdActivitiesGetResponse,
    GetActivitiesM3TerM3TerIdActivitiesGetError,
    GetActivitiesM3TerM3TerIdActivitiesGetResponse,
    ReturnType<typeof getActivitiesM3TerM3TerIdActivitiesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActivitiesM3TerM3TerIdActivitiesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActivitiesM3TerM3TerIdActivitiesGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getActivitiesM3TerM3TerIdActivitiesGetInfiniteQueryKey = (
  options: Options<GetActivitiesM3TerM3TerIdActivitiesGetData>,
): QueryKey<Options<GetActivitiesM3TerM3TerIdActivitiesGetData>> =>
  createQueryKey("getActivitiesM3TerM3TerIdActivitiesGet", options, true);

/**
 * Get Activities
 *
 * Get activities of a m3ter
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 */
export const getActivitiesM3TerM3TerIdActivitiesGetInfiniteOptions = (
  options: Options<GetActivitiesM3TerM3TerIdActivitiesGetData>,
) =>
  infiniteQueryOptions<
    GetActivitiesM3TerM3TerIdActivitiesGetResponse,
    GetActivitiesM3TerM3TerIdActivitiesGetError,
    InfiniteData<GetActivitiesM3TerM3TerIdActivitiesGetResponse>,
    QueryKey<Options<GetActivitiesM3TerM3TerIdActivitiesGetData>>,
    | string
    | null
    | Pick<
        QueryKey<Options<GetActivitiesM3TerM3TerIdActivitiesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetActivitiesM3TerM3TerIdActivitiesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  after: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getActivitiesM3TerM3TerIdActivitiesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getActivitiesM3TerM3TerIdActivitiesGetInfiniteQueryKey(options),
    },
  );

export const getProposalProposalTxHashGetQueryKey = (
  options: Options<GetProposalProposalTxHashGetData>,
) => createQueryKey("getProposalProposalTxHashGet", options);

/**
 * Get Proposal
 *
 * Retrieve proposal details by transaction hash.
 *
 * First checks the database cache. If not found, fetches from Ethereum
 * blockchain, decodes the transaction data, and caches the results.
 *
 * :param tx_hash: Ethereum transaction hash
 * :type tx_hash: str
 * :return: List of proposal meter readings
 */
export const getProposalProposalTxHashGetOptions = (
  options: Options<GetProposalProposalTxHashGetData>,
) =>
  queryOptions<
    GetProposalProposalTxHashGetResponse,
    GetProposalProposalTxHashGetError,
    GetProposalProposalTxHashGetResponse,
    ReturnType<typeof getProposalProposalTxHashGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProposalProposalTxHashGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProposalProposalTxHashGetQueryKey(options),
  });
