/* tslint:disable */
/* eslint-disable */
/**
 * M3terscan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Docstring for Activities
 */
export interface Activities {
    'timestamp': number;
    'energy': number;
    'signature': string;
}
/**
 * Docstring for ActivitiesResponse
 */
export interface ActivitiesResponse {
    'data': Array<Activities>;
    'limit': number;
    'next_cursor': string;
}
/**
 * Response model for daily enpoint.
 */
export interface DailyResponse {
    'hour_start_utc': string;
    'total_energy': number;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface LocationInner {
}
export interface MonthlyEnergyRead {
    'day': number;
    'month': number;
    'year': number;
    'total_energy': number;
}
/**
 * Represents the structured response containing a meter number, a formatted account ID, and a nonce value.
 */
export interface ProposalsResponse {
    'm3ter_no': number;
    'account': string;
    'nonce': number;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
}
/**
 * Response model for weekly enpoint.
 */
export interface WeeklyResponse {
    'day_of_week': number;
    'total_energy': number;
}
export interface WeeksEnergyRead {
    'year': number;
    'week': number;
    'total_energy': number;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get daily Batch
         * @summary Get Daily Batch
         * @param {Array<number>} meterIds Repeat param: ?meter_ids&#x3D;1&amp;meter_ids&#x3D;2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyBatchDailyBatchGet: async (meterIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterIds' is not null or undefined
            assertParamExists('getDailyBatchDailyBatchGet', 'meterIds', meterIds)
            const localVarPath = `/daily-batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (meterIds) {
                localVarQueryParameter['meter_ids'] = meterIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Welcome message to our users.
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readRootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Get daily Batch
         * @summary Get Daily Batch
         * @param {Array<number>} meterIds Repeat param: ?meter_ids&#x3D;1&amp;meter_ids&#x3D;2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDailyBatchDailyBatchGet(meterIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDailyBatchDailyBatchGet(meterIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getDailyBatchDailyBatchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Welcome message to our users.
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readRootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readRootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readRootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Get daily Batch
         * @summary Get Daily Batch
         * @param {Array<number>} meterIds Repeat param: ?meter_ids&#x3D;1&amp;meter_ids&#x3D;2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyBatchDailyBatchGet(meterIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getDailyBatchDailyBatchGet(meterIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Welcome message to our users.
         * @summary Read Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readRootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.readRootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * Get daily Batch
     * @summary Get Daily Batch
     * @param {Array<number>} meterIds Repeat param: ?meter_ids&#x3D;1&amp;meter_ids&#x3D;2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDailyBatchDailyBatchGet(meterIds: Array<number>, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDailyBatchDailyBatchGet(meterIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Welcome message to our users.
     * @summary Read Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public readRootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readRootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MeterApi - axios parameter creator
 */
export const MeterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get activities of a m3ter   :param m3ter_id: Description  :type m3ter_id: int
         * @summary Get Activities
         * @param {number} meterId 
         * @param {string | null} [after] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActivitiesMeterMeterIdActivitiesGet: async (meterId: number, after?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterId' is not null or undefined
            assertParamExists('getActivitiesMeterMeterIdActivitiesGet', 'meterId', meterId)
            const localVarPath = `/meter/{meter_id}/activities`
                .replace(`{${"meter_id"}}`, encodeURIComponent(String(meterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (after !== undefined) {
                localVarQueryParameter['after'] = after;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get daily energy usage aggregate.
         * @summary Get Daily
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyMeterMeterIdDailyGet: async (meterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterId' is not null or undefined
            assertParamExists('getDailyMeterMeterIdDailyGet', 'meterId', meterId)
            const localVarPath = `/meter/{meter_id}/daily`
                .replace(`{${"meter_id"}}`, encodeURIComponent(String(meterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get daily energy usage for a given month in a specified year.
         * @summary Get Month Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {number} month 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMonthOfYearMeterMeterIdMonthMonthYearGet: async (meterId: number, year: number, month: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterId' is not null or undefined
            assertParamExists('getMonthOfYearMeterMeterIdMonthMonthYearGet', 'meterId', meterId)
            // verify required parameter 'year' is not null or undefined
            assertParamExists('getMonthOfYearMeterMeterIdMonthMonthYearGet', 'year', year)
            // verify required parameter 'month' is not null or undefined
            assertParamExists('getMonthOfYearMeterMeterIdMonthMonthYearGet', 'month', month)
            const localVarPath = `/meter/{meter_id}/month/{month}/{year}`
                .replace(`{${"meter_id"}}`, encodeURIComponent(String(meterId)))
                .replace(`{${"year"}}`, encodeURIComponent(String(year)))
                .replace(`{${"month"}}`, encodeURIComponent(String(month)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get weekly energy usage aggregate.
         * @summary Get Weekly
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyMeterMeterIdWeeklyGet: async (meterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterId' is not null or undefined
            assertParamExists('getWeeklyMeterMeterIdWeeklyGet', 'meterId', meterId)
            const localVarPath = `/meter/{meter_id}/weekly`
                .replace(`{${"meter_id"}}`, encodeURIComponent(String(meterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get energy usage of all weeks of specified year.
         * @summary Get Weeks Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeksOfYearMeterMeterIdWeeksYearGet: async (meterId: number, year: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meterId' is not null or undefined
            assertParamExists('getWeeksOfYearMeterMeterIdWeeksYearGet', 'meterId', meterId)
            // verify required parameter 'year' is not null or undefined
            assertParamExists('getWeeksOfYearMeterMeterIdWeeksYearGet', 'year', year)
            const localVarPath = `/meter/{meter_id}/weeks/{year}`
                .replace(`{${"meter_id"}}`, encodeURIComponent(String(meterId)))
                .replace(`{${"year"}}`, encodeURIComponent(String(year)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeterApi - functional programming interface
 */
export const MeterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeterApiAxiosParamCreator(configuration)
    return {
        /**
         * Get activities of a m3ter   :param m3ter_id: Description  :type m3ter_id: int
         * @summary Get Activities
         * @param {number} meterId 
         * @param {string | null} [after] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getActivitiesMeterMeterIdActivitiesGet(meterId: number, after?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ActivitiesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getActivitiesMeterMeterIdActivitiesGet(meterId, after, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeterApi.getActivitiesMeterMeterIdActivitiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get daily energy usage aggregate.
         * @summary Get Daily
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDailyMeterMeterIdDailyGet(meterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DailyResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDailyMeterMeterIdDailyGet(meterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeterApi.getDailyMeterMeterIdDailyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get daily energy usage for a given month in a specified year.
         * @summary Get Month Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {number} month 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId: number, year: number, month: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MonthlyEnergyRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId, year, month, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeterApi.getMonthOfYearMeterMeterIdMonthMonthYearGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get weekly energy usage aggregate.
         * @summary Get Weekly
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeeklyMeterMeterIdWeeklyGet(meterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WeeklyResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeeklyMeterMeterIdWeeklyGet(meterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeterApi.getWeeklyMeterMeterIdWeeklyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get energy usage of all weeks of specified year.
         * @summary Get Weeks Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeeksOfYearMeterMeterIdWeeksYearGet(meterId: number, year: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WeeksEnergyRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeeksOfYearMeterMeterIdWeeksYearGet(meterId, year, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeterApi.getWeeksOfYearMeterMeterIdWeeksYearGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeterApi - factory interface
 */
export const MeterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeterApiFp(configuration)
    return {
        /**
         * Get activities of a m3ter   :param m3ter_id: Description  :type m3ter_id: int
         * @summary Get Activities
         * @param {number} meterId 
         * @param {string | null} [after] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActivitiesMeterMeterIdActivitiesGet(meterId: number, after?: string | null, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<ActivitiesResponse> {
            return localVarFp.getActivitiesMeterMeterIdActivitiesGet(meterId, after, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get daily energy usage aggregate.
         * @summary Get Daily
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyMeterMeterIdDailyGet(meterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<DailyResponse>> {
            return localVarFp.getDailyMeterMeterIdDailyGet(meterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get daily energy usage for a given month in a specified year.
         * @summary Get Month Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {number} month 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId: number, year: number, month: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MonthlyEnergyRead>> {
            return localVarFp.getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId, year, month, options).then((request) => request(axios, basePath));
        },
        /**
         * Get weekly energy usage aggregate.
         * @summary Get Weekly
         * @param {number} meterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyMeterMeterIdWeeklyGet(meterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<WeeklyResponse>> {
            return localVarFp.getWeeklyMeterMeterIdWeeklyGet(meterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get energy usage of all weeks of specified year.
         * @summary Get Weeks Of Year
         * @param {number} meterId 
         * @param {number} year 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeksOfYearMeterMeterIdWeeksYearGet(meterId: number, year: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<WeeksEnergyRead>> {
            return localVarFp.getWeeksOfYearMeterMeterIdWeeksYearGet(meterId, year, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeterApi - object-oriented interface
 */
export class MeterApi extends BaseAPI {
    /**
     * Get activities of a m3ter   :param m3ter_id: Description  :type m3ter_id: int
     * @summary Get Activities
     * @param {number} meterId 
     * @param {string | null} [after] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getActivitiesMeterMeterIdActivitiesGet(meterId: number, after?: string | null, limit?: number, options?: RawAxiosRequestConfig) {
        return MeterApiFp(this.configuration).getActivitiesMeterMeterIdActivitiesGet(meterId, after, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get daily energy usage aggregate.
     * @summary Get Daily
     * @param {number} meterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDailyMeterMeterIdDailyGet(meterId: number, options?: RawAxiosRequestConfig) {
        return MeterApiFp(this.configuration).getDailyMeterMeterIdDailyGet(meterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get daily energy usage for a given month in a specified year.
     * @summary Get Month Of Year
     * @param {number} meterId 
     * @param {number} year 
     * @param {number} month 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId: number, year: number, month: number, options?: RawAxiosRequestConfig) {
        return MeterApiFp(this.configuration).getMonthOfYearMeterMeterIdMonthMonthYearGet(meterId, year, month, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get weekly energy usage aggregate.
     * @summary Get Weekly
     * @param {number} meterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWeeklyMeterMeterIdWeeklyGet(meterId: number, options?: RawAxiosRequestConfig) {
        return MeterApiFp(this.configuration).getWeeklyMeterMeterIdWeeklyGet(meterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get energy usage of all weeks of specified year.
     * @summary Get Weeks Of Year
     * @param {number} meterId 
     * @param {number} year 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWeeksOfYearMeterMeterIdWeeksYearGet(meterId: number, year: number, options?: RawAxiosRequestConfig) {
        return MeterApiFp(this.configuration).getWeeksOfYearMeterMeterIdWeeksYearGet(meterId, year, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProposalApi - axios parameter creator
 */
export const ProposalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve proposal details by transaction hash.  First checks the database cache. If not found, fetches from Ethereum blockchain, decodes the transaction data, and caches the results.  :param tx_hash: Ethereum transaction hash :type tx_hash: str :return: List of proposal meter readings
         * @summary Get Proposal
         * @param {string} txHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProposalProposalTxHashGet: async (txHash: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txHash' is not null or undefined
            assertParamExists('getProposalProposalTxHashGet', 'txHash', txHash)
            const localVarPath = `/proposal/{tx_hash}`
                .replace(`{${"tx_hash"}}`, encodeURIComponent(String(txHash)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProposalApi - functional programming interface
 */
export const ProposalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProposalApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve proposal details by transaction hash.  First checks the database cache. If not found, fetches from Ethereum blockchain, decodes the transaction data, and caches the results.  :param tx_hash: Ethereum transaction hash :type tx_hash: str :return: List of proposal meter readings
         * @summary Get Proposal
         * @param {string} txHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProposalProposalTxHashGet(txHash: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProposalsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProposalProposalTxHashGet(txHash, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProposalApi.getProposalProposalTxHashGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProposalApi - factory interface
 */
export const ProposalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProposalApiFp(configuration)
    return {
        /**
         * Retrieve proposal details by transaction hash.  First checks the database cache. If not found, fetches from Ethereum blockchain, decodes the transaction data, and caches the results.  :param tx_hash: Ethereum transaction hash :type tx_hash: str :return: List of proposal meter readings
         * @summary Get Proposal
         * @param {string} txHash 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProposalProposalTxHashGet(txHash: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProposalsResponse>> {
            return localVarFp.getProposalProposalTxHashGet(txHash, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProposalApi - object-oriented interface
 */
export class ProposalApi extends BaseAPI {
    /**
     * Retrieve proposal details by transaction hash.  First checks the database cache. If not found, fetches from Ethereum blockchain, decodes the transaction data, and caches the results.  :param tx_hash: Ethereum transaction hash :type tx_hash: str :return: List of proposal meter readings
     * @summary Get Proposal
     * @param {string} txHash 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProposalProposalTxHashGet(txHash: string, options?: RawAxiosRequestConfig) {
        return ProposalApiFp(this.configuration).getProposalProposalTxHashGet(txHash, options).then((request) => request(this.axios, this.basePath));
    }
}



