// This file is auto-generated by @hey-api/openapi-ts

export const ActivitiesSchema = {
  properties: {
    timestamp: {
      type: "integer",
      title: "Timestamp",
    },
    energy: {
      type: "number",
      title: "Energy",
    },
    signature: {
      type: "string",
      title: "Signature",
    },
  },
  type: "object",
  required: ["timestamp", "energy", "signature"],
  title: "Activities",
  description: "Docstring for Activities",
} as const;

export const ActivitiesResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/Activities",
      },
      type: "array",
      title: "Data",
    },
    limit: {
      type: "integer",
      title: "Limit",
    },
    next_cursor: {
      type: "string",
      title: "Next Cursor",
    },
  },
  type: "object",
  required: ["data", "limit", "next_cursor"],
  title: "ActivitiesResponse",
  description: "Docstring for ActivitiesResponse",
} as const;

export const DailyResponseSchema = {
  properties: {
    hour_start_utc: {
      type: "string",
      title: "Hour Start Utc",
    },
    total_energy: {
      type: "number",
      title: "Total Energy",
    },
  },
  type: "object",
  required: ["hour_start_utc", "total_energy"],
  title: "DailyResponse",
  description: "Response model for daily enpoint.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const MonthOfYearResponseSchema = {
  properties: {
    day: {
      type: "integer",
      title: "Day",
    },
    total_energy: {
      type: "number",
      title: "Total Energy",
    },
  },
  type: "object",
  required: ["day", "total_energy"],
  title: "MonthOfYearResponse",
  description: "Response model to get a specified month of a specified year.",
} as const;

export const ProposalsResponseSchema = {
  properties: {
    m3ter_no: {
      type: "integer",
      title: "M3Ter No",
    },
    account: {
      type: "string",
      title: "Account",
    },
    nonce: {
      type: "integer",
      title: "Nonce",
    },
  },
  type: "object",
  required: ["m3ter_no", "account", "nonce"],
  title: "ProposalsResponse",
  description:
    "Represents the structured response containing a meter number,\na formatted account ID, and a nonce value.",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const WeeklyResponseSchema = {
  properties: {
    day_of_week: {
      type: "integer",
      title: "Day Of Week",
    },
    total_energy: {
      type: "number",
      title: "Total Energy",
    },
  },
  type: "object",
  required: ["day_of_week", "total_energy"],
  title: "WeeklyResponse",
  description: "Response model for weekly enpoint.",
} as const;

export const WeeksOfYearResponseSchema = {
  properties: {
    week: {
      type: "integer",
      title: "Week",
    },
    total_energy: {
      type: "number",
      title: "Total Energy",
    },
  },
  type: "object",
  required: ["week", "total_energy"],
  title: "WeeksOfYearResponse",
  description: "Response model to get weeks of a year.",
} as const;
