// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetActivitiesM3TerM3TerIdActivitiesGetData,
  GetActivitiesM3TerM3TerIdActivitiesGetErrors,
  GetActivitiesM3TerM3TerIdActivitiesGetResponses,
  GetDailyM3TerM3TerIdDailyGetData,
  GetDailyM3TerM3TerIdDailyGetErrors,
  GetDailyM3TerM3TerIdDailyGetResponses,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetErrors,
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponses,
  GetProposalProposalTxHashGetData,
  GetProposalProposalTxHashGetErrors,
  GetProposalProposalTxHashGetResponses,
  GetWeeklyM3TerM3TerIdWeeklyGetData,
  GetWeeklyM3TerM3TerIdWeeklyGetErrors,
  GetWeeklyM3TerM3TerIdWeeklyGetResponses,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetData,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetErrors,
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponses,
  ReadRootGetData,
  ReadRootGetResponses,
} from "./types.gen";
import {
  zGetActivitiesM3TerM3TerIdActivitiesGetData,
  zGetActivitiesM3TerM3TerIdActivitiesGetResponse,
  zGetDailyM3TerM3TerIdDailyGetData,
  zGetDailyM3TerM3TerIdDailyGetResponse,
  zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetData,
  zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse,
  zGetProposalProposalTxHashGetData,
  zGetProposalProposalTxHashGetResponse,
  zGetWeeklyM3TerM3TerIdWeeklyGetData,
  zGetWeeklyM3TerM3TerIdWeeklyGetResponse,
  zGetWeeksOfYearM3TerM3TerIdWeeksYearGetData,
  zGetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse,
  zReadRootGetData,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Read Root
 *
 * Welcome message to our beloved users.
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zReadRootGetData.parseAsync(data),
    url: "/",
    ...options,
  });

/**
 * Get Daily
 *
 * Get daily energy usage aggregate.
 */
export const getDailyM3TerM3TerIdDailyGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetDailyM3TerM3TerIdDailyGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDailyM3TerM3TerIdDailyGetResponses,
    GetDailyM3TerM3TerIdDailyGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetDailyM3TerM3TerIdDailyGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetDailyM3TerM3TerIdDailyGetResponse.parseAsync(data),
    url: "/m3ter/{m3ter_id}/daily",
    ...options,
  });

/**
 * Get Weekly
 *
 * Get weekly energy usage aggregate.
 */
export const getWeeklyM3TerM3TerIdWeeklyGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWeeklyM3TerM3TerIdWeeklyGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWeeklyM3TerM3TerIdWeeklyGetResponses,
    GetWeeklyM3TerM3TerIdWeeklyGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetWeeklyM3TerM3TerIdWeeklyGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetWeeklyM3TerM3TerIdWeeklyGetResponse.parseAsync(data),
    url: "/m3ter/{m3ter_id}/weekly",
    ...options,
  });

/**
 * Get Weeks Of Year
 *
 * Get energy usage of all weeks of specified year.
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 * :param year: Description
 * :type year: int
 */
export const getWeeksOfYearM3TerM3TerIdWeeksYearGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWeeksOfYearM3TerM3TerIdWeeksYearGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponses,
    GetWeeksOfYearM3TerM3TerIdWeeksYearGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetWeeksOfYearM3TerM3TerIdWeeksYearGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse.parseAsync(data),
    url: "/m3ter/{m3ter_id}/weeks/{year}",
    ...options,
  });

/**
 * Get Month Of Year
 *
 * Get energy usage of a month in specified year.
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 * :param year: Description
 * :type year: int
 * :param month: Description
 * :type month: int
 */
export const getMonthOfYearM3TerM3TerIdMonthYearMonthGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponses,
    GetMonthOfYearM3TerM3TerIdMonthYearMonthGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse.parseAsync(
        data,
      ),
    url: "/m3ter/{m3ter_id}/month/{year}/{month}",
    ...options,
  });

/**
 * Get Activities
 *
 * Get activities of a m3ter
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 */
export const getActivitiesM3TerM3TerIdActivitiesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetActivitiesM3TerM3TerIdActivitiesGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetActivitiesM3TerM3TerIdActivitiesGetResponses,
    GetActivitiesM3TerM3TerIdActivitiesGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetActivitiesM3TerM3TerIdActivitiesGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetActivitiesM3TerM3TerIdActivitiesGetResponse.parseAsync(data),
    url: "/m3ter/{m3ter_id}/activities",
    ...options,
  });

/**
 * Get Proposal
 *
 * Retrieve proposal details by transaction hash.
 *
 * First checks the database cache. If not found, fetches from Ethereum
 * blockchain, decodes the transaction data, and caches the results.
 *
 * :param tx_hash: Ethereum transaction hash
 * :type tx_hash: str
 * :return: List of proposal meter readings
 */
export const getProposalProposalTxHashGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProposalProposalTxHashGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProposalProposalTxHashGetResponses,
    GetProposalProposalTxHashGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetProposalProposalTxHashGetData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetProposalProposalTxHashGetResponse.parseAsync(data),
    url: "/proposal/{tx_hash}",
    ...options,
  });
