// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:8000" | (string & {});
};

/**
 * Activities
 *
 * Docstring for Activities
 */
export type Activities = {
  /**
   * Timestamp
   */
  timestamp: number;
  /**
   * Energy
   */
  energy: number;
  /**
   * Signature
   */
  signature: string;
};

/**
 * ActivitiesResponse
 *
 * Docstring for ActivitiesResponse
 */
export type ActivitiesResponse = {
  /**
   * Data
   */
  data: Array<Activities>;
  /**
   * Limit
   */
  limit: number;
  /**
   * Next Cursor
   */
  next_cursor: string;
};

/**
 * DailyResponse
 *
 * Response model for daily enpoint.
 */
export type DailyResponse = {
  /**
   * Hour Start Utc
   */
  hour_start_utc: string;
  /**
   * Total Energy
   */
  total_energy: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MonthOfYearResponse
 *
 * Response model to get a specified month of a specified year.
 */
export type MonthOfYearResponse = {
  /**
   * Day
   */
  day: number;
  /**
   * Total Energy
   */
  total_energy: number;
};

/**
 * ProposalsResponse
 *
 * Represents the structured response containing a meter number,
 * a formatted account ID, and a nonce value.
 */
export type ProposalsResponse = {
  /**
   * M3Ter No
   */
  m3ter_no: number;
  /**
   * Account
   */
  account: string;
  /**
   * Nonce
   */
  nonce: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * WeeklyResponse
 *
 * Response model for weekly enpoint.
 */
export type WeeklyResponse = {
  /**
   * Day Of Week
   */
  day_of_week: number;
  /**
   * Total Energy
   */
  total_energy: number;
};

/**
 * WeeksOfYearResponse
 *
 * Response model to get weeks of a year.
 */
export type WeeksOfYearResponse = {
  /**
   * Week
   */
  week: number;
  /**
   * Total Energy
   */
  total_energy: number;
};

export type ReadRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetDailyM3TerM3TerIdDailyGetData = {
  body?: never;
  path: {
    /**
     * M3Ter Id
     */
    m3ter_id: number;
  };
  query?: never;
  url: "/m3ter/{m3ter_id}/daily";
};

export type GetDailyM3TerM3TerIdDailyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDailyM3TerM3TerIdDailyGetError =
  GetDailyM3TerM3TerIdDailyGetErrors[keyof GetDailyM3TerM3TerIdDailyGetErrors];

export type GetDailyM3TerM3TerIdDailyGetResponses = {
  /**
   * Response Get Daily M3Ter  M3Ter Id  Daily Get
   *
   * Successful Response
   */
  200: Array<DailyResponse>;
};

export type GetDailyM3TerM3TerIdDailyGetResponse =
  GetDailyM3TerM3TerIdDailyGetResponses[keyof GetDailyM3TerM3TerIdDailyGetResponses];

export type GetWeeklyM3TerM3TerIdWeeklyGetData = {
  body?: never;
  path: {
    /**
     * M3Ter Id
     */
    m3ter_id: number;
  };
  query?: never;
  url: "/m3ter/{m3ter_id}/weekly";
};

export type GetWeeklyM3TerM3TerIdWeeklyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWeeklyM3TerM3TerIdWeeklyGetError =
  GetWeeklyM3TerM3TerIdWeeklyGetErrors[keyof GetWeeklyM3TerM3TerIdWeeklyGetErrors];

export type GetWeeklyM3TerM3TerIdWeeklyGetResponses = {
  /**
   * Response Get Weekly M3Ter  M3Ter Id  Weekly Get
   *
   * Successful Response
   */
  200: Array<WeeklyResponse>;
};

export type GetWeeklyM3TerM3TerIdWeeklyGetResponse =
  GetWeeklyM3TerM3TerIdWeeklyGetResponses[keyof GetWeeklyM3TerM3TerIdWeeklyGetResponses];

export type GetWeeksOfYearM3TerM3TerIdWeeksYearGetData = {
  body?: never;
  path: {
    /**
     * M3Ter Id
     */
    m3ter_id: number;
    /**
     * Year
     */
    year: number;
  };
  query?: never;
  url: "/m3ter/{m3ter_id}/weeks/{year}";
};

export type GetWeeksOfYearM3TerM3TerIdWeeksYearGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWeeksOfYearM3TerM3TerIdWeeksYearGetError =
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetErrors[keyof GetWeeksOfYearM3TerM3TerIdWeeksYearGetErrors];

export type GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponses = {
  /**
   * Response Get Weeks Of Year M3Ter  M3Ter Id  Weeks  Year  Get
   *
   * Successful Response
   */
  200: Array<WeeksOfYearResponse>;
};

export type GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse =
  GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponses[keyof GetWeeksOfYearM3TerM3TerIdWeeksYearGetResponses];

export type GetMonthOfYearM3TerM3TerIdMonthYearMonthGetData = {
  body?: never;
  path: {
    /**
     * M3Ter Id
     */
    m3ter_id: number;
    /**
     * Year
     */
    year: number;
    /**
     * Month
     */
    month: number;
  };
  query?: never;
  url: "/m3ter/{m3ter_id}/month/{year}/{month}";
};

export type GetMonthOfYearM3TerM3TerIdMonthYearMonthGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMonthOfYearM3TerM3TerIdMonthYearMonthGetError =
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetErrors[keyof GetMonthOfYearM3TerM3TerIdMonthYearMonthGetErrors];

export type GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponses = {
  /**
   * Response Get Month Of Year M3Ter  M3Ter Id  Month  Year   Month  Get
   *
   * Successful Response
   */
  200: Array<MonthOfYearResponse>;
};

export type GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse =
  GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponses[keyof GetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponses];

export type GetActivitiesM3TerM3TerIdActivitiesGetData = {
  body?: never;
  path: {
    /**
     * M3Ter Id
     */
    m3ter_id: number;
  };
  query?: {
    /**
     * After
     */
    after?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/m3ter/{m3ter_id}/activities";
};

export type GetActivitiesM3TerM3TerIdActivitiesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetActivitiesM3TerM3TerIdActivitiesGetError =
  GetActivitiesM3TerM3TerIdActivitiesGetErrors[keyof GetActivitiesM3TerM3TerIdActivitiesGetErrors];

export type GetActivitiesM3TerM3TerIdActivitiesGetResponses = {
  /**
   * Successful Response
   */
  200: ActivitiesResponse;
};

export type GetActivitiesM3TerM3TerIdActivitiesGetResponse =
  GetActivitiesM3TerM3TerIdActivitiesGetResponses[keyof GetActivitiesM3TerM3TerIdActivitiesGetResponses];

export type GetProposalProposalTxHashGetData = {
  body?: never;
  path: {
    /**
     * Tx Hash
     */
    tx_hash: string;
  };
  query?: never;
  url: "/proposal/{tx_hash}";
};

export type GetProposalProposalTxHashGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProposalProposalTxHashGetError =
  GetProposalProposalTxHashGetErrors[keyof GetProposalProposalTxHashGetErrors];

export type GetProposalProposalTxHashGetResponses = {
  /**
   * Response Get Proposal Proposal  Tx Hash  Get
   *
   * Successful Response
   */
  200: Array<ProposalsResponse>;
};

export type GetProposalProposalTxHashGetResponse =
  GetProposalProposalTxHashGetResponses[keyof GetProposalProposalTxHashGetResponses];
