// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Activities
 *
 * Docstring for Activities
 */
export const zActivities = z.object({
  timestamp: z.int(),
  energy: z.number(),
  signature: z.string(),
});

/**
 * ActivitiesResponse
 *
 * Docstring for ActivitiesResponse
 */
export const zActivitiesResponse = z.object({
  data: z.array(zActivities),
  limit: z.int(),
  next_cursor: z.string(),
});

/**
 * DailyResponse
 *
 * Response model for daily enpoint.
 */
export const zDailyResponse = z.object({
  hour_start_utc: z.string(),
  total_energy: z.number(),
});

/**
 * MonthOfYearResponse
 *
 * Response model to get a specified month of a specified year.
 */
export const zMonthOfYearResponse = z.object({
  day: z.int(),
  total_energy: z.number(),
});

/**
 * ProposalsResponse
 *
 * Represents the structured response containing a meter number,
 * a formatted account ID, and a nonce value.
 */
export const zProposalsResponse = z.object({
  m3ter_no: z.int(),
  account: z.string(),
  nonce: z.int(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

/**
 * WeeklyResponse
 *
 * Response model for weekly enpoint.
 */
export const zWeeklyResponse = z.object({
  day_of_week: z.int(),
  total_energy: z.number(),
});

/**
 * WeeksOfYearResponse
 *
 * Response model to get weeks of a year.
 */
export const zWeeksOfYearResponse = z.object({
  week: z.int(),
  total_energy: z.number(),
});

export const zReadRootGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetDailyM3TerM3TerIdDailyGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    m3ter_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Daily M3Ter  M3Ter Id  Daily Get
 *
 * Successful Response
 */
export const zGetDailyM3TerM3TerIdDailyGetResponse = z.array(zDailyResponse);

export const zGetWeeklyM3TerM3TerIdWeeklyGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    m3ter_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Weekly M3Ter  M3Ter Id  Weekly Get
 *
 * Successful Response
 */
export const zGetWeeklyM3TerM3TerIdWeeklyGetResponse = z.array(zWeeklyResponse);

export const zGetWeeksOfYearM3TerM3TerIdWeeksYearGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    m3ter_id: z.int(),
    year: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Weeks Of Year M3Ter  M3Ter Id  Weeks  Year  Get
 *
 * Successful Response
 */
export const zGetWeeksOfYearM3TerM3TerIdWeeksYearGetResponse =
  z.array(zWeeksOfYearResponse);

export const zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    m3ter_id: z.int(),
    year: z.int(),
    month: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Month Of Year M3Ter  M3Ter Id  Month  Year   Month  Get
 *
 * Successful Response
 */
export const zGetMonthOfYearM3TerM3TerIdMonthYearMonthGetResponse =
  z.array(zMonthOfYearResponse);

export const zGetActivitiesM3TerM3TerIdActivitiesGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    m3ter_id: z.int(),
  }),
  query: z.optional(
    z.object({
      after: z.optional(z.union([z.string(), z.null()])),
      limit: z.optional(z.int()).default(10),
    }),
  ),
});

/**
 * Successful Response
 */
export const zGetActivitiesM3TerM3TerIdActivitiesGetResponse =
  zActivitiesResponse;

export const zGetProposalProposalTxHashGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tx_hash: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Proposal Proposal  Tx Hash  Get
 *
 * Successful Response
 */
export const zGetProposalProposalTxHashGetResponse =
  z.array(zProposalsResponse);
