/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as M3terM3terIdRouteRouteImport } from './routes/m3ter/$m3terId/route'
import { Route as AppProposalHashRouteImport } from './routes/_app/proposal/$hash'
import { Route as AppProposalLatestRouteImport } from './routes/_app/proposal/latest'
import { Route as M3terM3terIdActivitiesRouteImport } from './routes/m3ter/$m3terId/activities'
import { Route as M3terM3terIdAskAiRouteImport } from './routes/m3ter/$m3terId/ask-ai'
import { Route as M3terM3terIdChartsRouteImport } from './routes/m3ter/$m3terId/charts'
import { Route as M3terM3terIdOverviewRouteImport } from './routes/m3ter/$m3terId/overview'
import { Route as M3terM3terIdTradesRouteImport } from './routes/m3ter/$m3terId/trades'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const M3terM3terIdRouteRoute = M3terM3terIdRouteRouteImport.update({
  id: '/m3ter/$m3terId',
  path: '/m3ter/$m3terId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProposalHashRoute = AppProposalHashRouteImport.update({
  id: '/proposal/$hash',
  path: '/proposal/$hash',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalLatestRoute = AppProposalLatestRouteImport.update({
  id: '/proposal/latest',
  path: '/proposal/latest',
  getParentRoute: () => AppRoute,
} as any)
const M3terM3terIdActivitiesRoute = M3terM3terIdActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => M3terM3terIdRouteRoute,
} as any)
const M3terM3terIdAskAiRoute = M3terM3terIdAskAiRouteImport.update({
  id: '/ask-ai',
  path: '/ask-ai',
  getParentRoute: () => M3terM3terIdRouteRoute,
} as any)
const M3terM3terIdChartsRoute = M3terM3terIdChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => M3terM3terIdRouteRoute,
} as any)
const M3terM3terIdOverviewRoute = M3terM3terIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => M3terM3terIdRouteRoute,
} as any)
const M3terM3terIdTradesRoute = M3terM3terIdTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => M3terM3terIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/m3ter/$m3terId': typeof M3terM3terIdRouteRouteWithChildren
  '/proposal/$hash': typeof AppProposalHashRoute
  '/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRoutesByTo {
  '/m3ter/$m3terId': typeof M3terM3terIdRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/proposal/$hash': typeof AppProposalHashRoute
  '/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/m3ter/$m3terId': typeof M3terM3terIdRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/proposal/$hash': typeof AppProposalHashRoute
  '/_app/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m3ter/$m3terId'
    | '/proposal/$hash'
    | '/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/m3ter/$m3terId'
    | '/'
    | '/proposal/$hash'
    | '/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  id:
    | '__root__'
    | '/_app'
    | '/m3ter/$m3terId'
    | '/_app/'
    | '/_app/proposal/$hash'
    | '/_app/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  M3terM3terIdRouteRoute: typeof M3terM3terIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m3ter/$m3terId': {
      id: '/m3ter/$m3terId'
      path: '/m3ter/$m3terId'
      fullPath: '/m3ter/$m3terId'
      preLoaderRoute: typeof M3terM3terIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/proposal/$hash': {
      id: '/_app/proposal/$hash'
      path: '/proposal/$hash'
      fullPath: '/proposal/$hash'
      preLoaderRoute: typeof AppProposalHashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposal/latest': {
      id: '/_app/proposal/latest'
      path: '/proposal/latest'
      fullPath: '/proposal/latest'
      preLoaderRoute: typeof AppProposalLatestRouteImport
      parentRoute: typeof AppRoute
    }
    '/m3ter/$m3terId/activities': {
      id: '/m3ter/$m3terId/activities'
      path: '/activities'
      fullPath: '/m3ter/$m3terId/activities'
      preLoaderRoute: typeof M3terM3terIdActivitiesRouteImport
      parentRoute: typeof M3terM3terIdRouteRoute
    }
    '/m3ter/$m3terId/ask-ai': {
      id: '/m3ter/$m3terId/ask-ai'
      path: '/ask-ai'
      fullPath: '/m3ter/$m3terId/ask-ai'
      preLoaderRoute: typeof M3terM3terIdAskAiRouteImport
      parentRoute: typeof M3terM3terIdRouteRoute
    }
    '/m3ter/$m3terId/charts': {
      id: '/m3ter/$m3terId/charts'
      path: '/charts'
      fullPath: '/m3ter/$m3terId/charts'
      preLoaderRoute: typeof M3terM3terIdChartsRouteImport
      parentRoute: typeof M3terM3terIdRouteRoute
    }
    '/m3ter/$m3terId/overview': {
      id: '/m3ter/$m3terId/overview'
      path: '/overview'
      fullPath: '/m3ter/$m3terId/overview'
      preLoaderRoute: typeof M3terM3terIdOverviewRouteImport
      parentRoute: typeof M3terM3terIdRouteRoute
    }
    '/m3ter/$m3terId/trades': {
      id: '/m3ter/$m3terId/trades'
      path: '/trades'
      fullPath: '/m3ter/$m3terId/trades'
      preLoaderRoute: typeof M3terM3terIdTradesRouteImport
      parentRoute: typeof M3terM3terIdRouteRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProposalHashRoute: typeof AppProposalHashRoute
  AppProposalLatestRoute: typeof AppProposalLatestRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProposalHashRoute: AppProposalHashRoute,
  AppProposalLatestRoute: AppProposalLatestRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface M3terM3terIdRouteRouteChildren {
  M3terM3terIdActivitiesRoute: typeof M3terM3terIdActivitiesRoute
  M3terM3terIdAskAiRoute: typeof M3terM3terIdAskAiRoute
  M3terM3terIdChartsRoute: typeof M3terM3terIdChartsRoute
  M3terM3terIdOverviewRoute: typeof M3terM3terIdOverviewRoute
  M3terM3terIdTradesRoute: typeof M3terM3terIdTradesRoute
}

const M3terM3terIdRouteRouteChildren: M3terM3terIdRouteRouteChildren = {
  M3terM3terIdActivitiesRoute: M3terM3terIdActivitiesRoute,
  M3terM3terIdAskAiRoute: M3terM3terIdAskAiRoute,
  M3terM3terIdChartsRoute: M3terM3terIdChartsRoute,
  M3terM3terIdOverviewRoute: M3terM3terIdOverviewRoute,
  M3terM3terIdTradesRoute: M3terM3terIdTradesRoute,
}

const M3terM3terIdRouteRouteWithChildren =
  M3terM3terIdRouteRoute._addFileChildren(M3terM3terIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  M3terM3terIdRouteRoute: M3terM3terIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
