/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as M3terRouteImport } from './routes/m3ter'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProposalHashRouteImport } from './routes/_app/proposal/$hash'
import { Route as AppProposalLatestRouteImport } from './routes/_app/proposal/latest'
import { Route as M3terM3terIdActivitiesRouteImport } from './routes/m3ter/$m3terId/activities'
import { Route as M3terM3terIdAskAiRouteImport } from './routes/m3ter/$m3terId/ask-ai'
import { Route as M3terM3terIdChartsRouteImport } from './routes/m3ter/$m3terId/charts'
import { Route as M3terM3terIdOverviewRouteImport } from './routes/m3ter/$m3terId/overview'
import { Route as M3terM3terIdTradesRouteImport } from './routes/m3ter/$m3terId/trades'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const M3terRoute = M3terRouteImport.update({
  id: '/m3ter',
  path: '/m3ter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalHashRoute = AppProposalHashRouteImport.update({
  id: '/proposal/$hash',
  path: '/proposal/$hash',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalLatestRoute = AppProposalLatestRouteImport.update({
  id: '/proposal/latest',
  path: '/proposal/latest',
  getParentRoute: () => AppRoute,
} as any)
const M3terM3terIdActivitiesRoute = M3terM3terIdActivitiesRouteImport.update({
  id: '/$m3terId/activities',
  path: '/$m3terId/activities',
  getParentRoute: () => M3terRoute,
} as any)
const M3terM3terIdAskAiRoute = M3terM3terIdAskAiRouteImport.update({
  id: '/$m3terId/ask-ai',
  path: '/$m3terId/ask-ai',
  getParentRoute: () => M3terRoute,
} as any)
const M3terM3terIdChartsRoute = M3terM3terIdChartsRouteImport.update({
  id: '/$m3terId/charts',
  path: '/$m3terId/charts',
  getParentRoute: () => M3terRoute,
} as any)
const M3terM3terIdOverviewRoute = M3terM3terIdOverviewRouteImport.update({
  id: '/$m3terId/overview',
  path: '/$m3terId/overview',
  getParentRoute: () => M3terRoute,
} as any)
const M3terM3terIdTradesRoute = M3terM3terIdTradesRouteImport.update({
  id: '/$m3terId/trades',
  path: '/$m3terId/trades',
  getParentRoute: () => M3terRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/m3ter': typeof M3terRouteWithChildren
  '/proposal/$hash': typeof AppProposalHashRoute
  '/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRoutesByTo {
  '/m3ter': typeof M3terRouteWithChildren
  '/': typeof AppIndexRoute
  '/proposal/$hash': typeof AppProposalHashRoute
  '/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/m3ter': typeof M3terRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/proposal/$hash': typeof AppProposalHashRoute
  '/_app/proposal/latest': typeof AppProposalLatestRoute
  '/m3ter/$m3terId/activities': typeof M3terM3terIdActivitiesRoute
  '/m3ter/$m3terId/ask-ai': typeof M3terM3terIdAskAiRoute
  '/m3ter/$m3terId/charts': typeof M3terM3terIdChartsRoute
  '/m3ter/$m3terId/overview': typeof M3terM3terIdOverviewRoute
  '/m3ter/$m3terId/trades': typeof M3terM3terIdTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m3ter'
    | '/proposal/$hash'
    | '/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/m3ter'
    | '/'
    | '/proposal/$hash'
    | '/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  id:
    | '__root__'
    | '/_app'
    | '/m3ter'
    | '/_app/'
    | '/_app/proposal/$hash'
    | '/_app/proposal/latest'
    | '/m3ter/$m3terId/activities'
    | '/m3ter/$m3terId/ask-ai'
    | '/m3ter/$m3terId/charts'
    | '/m3ter/$m3terId/overview'
    | '/m3ter/$m3terId/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  M3terRoute: typeof M3terRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m3ter': {
      id: '/m3ter'
      path: '/m3ter'
      fullPath: '/m3ter'
      preLoaderRoute: typeof M3terRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposal/$hash': {
      id: '/_app/proposal/$hash'
      path: '/proposal/$hash'
      fullPath: '/proposal/$hash'
      preLoaderRoute: typeof AppProposalHashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposal/latest': {
      id: '/_app/proposal/latest'
      path: '/proposal/latest'
      fullPath: '/proposal/latest'
      preLoaderRoute: typeof AppProposalLatestRouteImport
      parentRoute: typeof AppRoute
    }
    '/m3ter/$m3terId/activities': {
      id: '/m3ter/$m3terId/activities'
      path: '/$m3terId/activities'
      fullPath: '/m3ter/$m3terId/activities'
      preLoaderRoute: typeof M3terM3terIdActivitiesRouteImport
      parentRoute: typeof M3terRoute
    }
    '/m3ter/$m3terId/ask-ai': {
      id: '/m3ter/$m3terId/ask-ai'
      path: '/$m3terId/ask-ai'
      fullPath: '/m3ter/$m3terId/ask-ai'
      preLoaderRoute: typeof M3terM3terIdAskAiRouteImport
      parentRoute: typeof M3terRoute
    }
    '/m3ter/$m3terId/charts': {
      id: '/m3ter/$m3terId/charts'
      path: '/$m3terId/charts'
      fullPath: '/m3ter/$m3terId/charts'
      preLoaderRoute: typeof M3terM3terIdChartsRouteImport
      parentRoute: typeof M3terRoute
    }
    '/m3ter/$m3terId/overview': {
      id: '/m3ter/$m3terId/overview'
      path: '/$m3terId/overview'
      fullPath: '/m3ter/$m3terId/overview'
      preLoaderRoute: typeof M3terM3terIdOverviewRouteImport
      parentRoute: typeof M3terRoute
    }
    '/m3ter/$m3terId/trades': {
      id: '/m3ter/$m3terId/trades'
      path: '/$m3terId/trades'
      fullPath: '/m3ter/$m3terId/trades'
      preLoaderRoute: typeof M3terM3terIdTradesRouteImport
      parentRoute: typeof M3terRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProposalHashRoute: typeof AppProposalHashRoute
  AppProposalLatestRoute: typeof AppProposalLatestRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProposalHashRoute: AppProposalHashRoute,
  AppProposalLatestRoute: AppProposalLatestRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface M3terRouteChildren {
  M3terM3terIdActivitiesRoute: typeof M3terM3terIdActivitiesRoute
  M3terM3terIdAskAiRoute: typeof M3terM3terIdAskAiRoute
  M3terM3terIdChartsRoute: typeof M3terM3terIdChartsRoute
  M3terM3terIdOverviewRoute: typeof M3terM3terIdOverviewRoute
  M3terM3terIdTradesRoute: typeof M3terM3terIdTradesRoute
}

const M3terRouteChildren: M3terRouteChildren = {
  M3terM3terIdActivitiesRoute: M3terM3terIdActivitiesRoute,
  M3terM3terIdAskAiRoute: M3terM3terIdAskAiRoute,
  M3terM3terIdChartsRoute: M3terM3terIdChartsRoute,
  M3terM3terIdOverviewRoute: M3terM3terIdOverviewRoute,
  M3terM3terIdTradesRoute: M3terM3terIdTradesRoute,
}

const M3terRouteWithChildren = M3terRoute._addFileChildren(M3terRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  M3terRoute: M3terRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
